version: "3.7"
services:
  api:
    image: "marquezproject/marquez:${TAG}"
    container_name: marquez-api
    environment:
      - MARQUEZ_PORT=${API_PORT}
      - MARQUEZ_ADMIN_PORT=${API_ADMIN_PORT}
      - MARQUEZ_CONFIG=${MARQUEZ_CONFIG}
    ports:
      - "${API_PORT}:${API_PORT}"
      - "${API_ADMIN_PORT}:${API_ADMIN_PORT}"
    volumes:
      - data:/opt/marquez
    links:
      - "db:postgres"
    depends_on:
      - db
    entrypoint: ["/opt/marquez/wait-for-it.sh", "db:5432", "--", "./entrypoint.sh"]

  db:
    image: postgres:14
    container_name: marquez-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MARQUEZ_DB=${MARQUEZ_DB}
      - MARQUEZ_USER=${MARQUEZ_USER}
      - MARQUEZ_PASSWORD=${MARQUEZ_PASSWORD}
    volumes:
      - db-conf:/etc/postgresql
      - db-init:/docker-entrypoint-initdb.d
      - db-backup:/var/lib/postgresql/data
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    # Enables SQL statement logging (see: https://www.postgresql.org/docs/12/runtime-config-logging.html#GUC-LOG-STATEMENT)
    # command: ["postgres", "-c", "log_statement=all"]

volumes:
  data:
  db-conf:
  db-init:
  db-backup:
